// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp4OeBzRdMm4WCRvOCoUSXjWq1vLiebK8',
    appId: '1:296748460878:web:03127044d12526cb41cc1f',
    messagingSenderId: '296748460878',
    projectId: 'my-ecommerce-app-verfection',
    authDomain: 'my-ecommerce-app-verfection.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-verfection.firebasestorage.app',
    measurementId: 'G-SKGZFE020D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGT2gdG_ckJh2ROlMzp1t4Kkyys627C08',
    appId: '1:296748460878:android:8b9606910fb034c841cc1f',
    messagingSenderId: '296748460878',
    projectId: 'my-ecommerce-app-verfection',
    storageBucket: 'my-ecommerce-app-verfection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEM6EFZFh7ZTtsAH7Y8sq8EzLhvUmaZi4',
    appId: '1:296748460878:ios:0adc7e1c6e8ea6b541cc1f',
    messagingSenderId: '296748460878',
    projectId: 'my-ecommerce-app-verfection',
    storageBucket: 'my-ecommerce-app-verfection.firebasestorage.app',
    iosBundleId: 'com.example.appStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEM6EFZFh7ZTtsAH7Y8sq8EzLhvUmaZi4',
    appId: '1:296748460878:ios:0adc7e1c6e8ea6b541cc1f',
    messagingSenderId: '296748460878',
    projectId: 'my-ecommerce-app-verfection',
    storageBucket: 'my-ecommerce-app-verfection.firebasestorage.app',
    iosBundleId: 'com.example.appStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp4OeBzRdMm4WCRvOCoUSXjWq1vLiebK8',
    appId: '1:296748460878:web:d8db8e68d7af5fc841cc1f',
    messagingSenderId: '296748460878',
    projectId: 'my-ecommerce-app-verfection',
    authDomain: 'my-ecommerce-app-verfection.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-verfection.firebasestorage.app',
    measurementId: 'G-6D05CGF1HL',
  );
}
